resources:
- ../../base/app
- sealed-secret.yaml

namespace: argocd
namePrefix: argocd-

images:
- name: 061039804626.dkr.ecr.ap-northeast-2.amazonaws.com/matchfit-ecr
  newTag: f26abe6
- name: alex62626/matchfit
  newName: alex62626/matchfit
  newTag: 783e67c
- name: your-registry/your-repo
  newTag: dev-${SHORT_SHA}

configMapGenerator:
- envs:
  - argocd.env
  name: env-vars

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
