resources:
- ../../base/app


images:
- name: your-registry/your-repo
  newTag: dev-${SHORT_SHA}


configMapGenerator:
- literals:
  - SPRING_PROFILES_ACTIVE=dev
  name: app-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
