apiVersion: autoscaling/v2         # HPA의 API 버전
kind: HorizontalPodAutoscaler      # 리소스 종류는 HPA
metadata:
  name: backend-hpa                # HPA 리소스의 이름
  namespace: argocd               # 적용할 네임스페이스. Deployment와 동일해야 함
spec:
  scaleTargetRef:                  # HPA가 확장/축소할 대상 리소스를 지정
    apiVersion: apps/v1            # 타겟 리소스의 API 버전
    kind: Deployment               # 리소스 종류
    name: argocd-backend           # 타겟 Deployment 이름
  minReplicas: 2                   # 최소 Pod 개수
  maxReplicas: 10                  # 최대 Pod 개수
  metrics:                         # 스케일 기준 메트릭 정의
    - type: Resource               # 리소스 기반 메트릭
      resource:
        name: cpu                  # 측정할 리소스는 CPU
        target:
          type: Utilization        # 메트릭 타입: 사용률 기반
          averageUtilization: 50   # 평균 CPU 사용률이 70% 넘으면 스케일 아웃, 낮으면 스케일 인
