---
apiVersion: v1
kind: Service
metadata:
  name: argocd-application-controller-metrics
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-application-controller-metrics
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/part-of: argocd
  ports:
    - name: metrics
      port: 8082
      targetPort: 8082
      protocol: TCP

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-application-controller-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-application-controller-metrics
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scheme: http
