# base/monitoring/crds-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom-crds
  namespace: monitoring
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.60.0
    targetRevision: v0.60.0
    path: bundle.yaml         # CRD 정의가 담긴 bundle
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring      # CRD 는 네임스페이스 무관, 관례상 지정
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
