# base/monitoring/crds-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # 가장 먼저 실행
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts
    chart: prometheus-operator-crds
    targetRevision: 8.0.1 
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false  # CRD는 prune하지 않음 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
