{
 "title": "FluentBit Log",
 "tags": [ "matchfit" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Log",
   "type": "table",
   "description": "전체 로그 패널",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\r\n| sort @timestamp desc\r\n| limit 100\r\n",
     "logGroups": [
      {
       "accountId": "061039804626",
       "arn": "arn:aws:logs:ap-northeast-2:061039804626:log-group:/matchfit-fluentbit/logs:*",
       "name": "/matchfit-fluentbit/logs"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Error",
   "type": "table",
   "description": "에러, 예외, 실패 관련 로그만 표시",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\r\n| filter @message like /(?i)(ERROR|Exception|Fail)/\r\n| sort @timestamp desc\r\n| limit 100\r\n",
     "logGroups": [
      {
       "accountId": "061039804626",
       "arn": "arn:aws:logs:ap-northeast-2:061039804626:log-group:/matchfit-fluentbit/logs:*",
       "name": "/matchfit-fluentbit/logs"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Error count over time",
   "type": "timeseries",
   "description": "시간별 에러 수 ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expression": "filter @message like /(?i)(ERROR|Exception|Fail)/\r\n| stats count(*) as error_count by bin(1m)\r\n",
     "logGroups": [
      {
       "accountId": "061039804626",
       "arn": "arn:aws:logs:ap-northeast-2:061039804626:log-group:/matchfit-fluentbit/logs:*",
       "name": "/matchfit-fluentbit/logs"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  }
 ]
}