apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prom-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "58.3.0" # 최신 버전 확인 필요
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  values:
    grafana:
      ingress:
        enabled: false  # ALB로 따로 구성했으므로
    prometheus:
      serviceMonitor:
        selfMonitor: true
