resources:
  - grafana-alb.yaml
  - service-monitor.yaml
  - fluentbit-rbac.yaml
  - fluentbit-configmap.yaml
  - fluentbit-daemonset.yaml


helmCharts:
  - name: kube-prometheus-stack
    namespace: monitoring
    valuesFile: ./grafana-values.yaml
