apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: matchfit-backend
  namespace: monitoring
  labels:
    app: matchfit
    release: kube-prometheus-stack   # ← 이거 추가
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - argocd
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s
