# values.yaml
# 1) Prometheus가 CRD ServiceMonitor를 어떻게 선택할지
prometheus:
  prometheusSpec:
    # Helm chart 안에 serviceMonitorSelector가 없을 때
    # "Helm values"(default) 기준으로 Nil selector를 허용할지 여부
    serviceMonitorSelectorNilUsesHelmValues: false

# 2) Grafana, Alertmanager 외부 노출(INGRESS) 비활성화
grafana:
  ingress:
    enabled: false

alertmanager:
  ingress:
    enabled: false
