 apiVersion: v1
 kind: ConfigMap
 metadata:
   name: k6-script
 data:
   script.js: |-
 {{- if eq .Values.testMode "full" }}
 {{ .Values.script_full | nindent 4 }}
 {{- else }}
 {{ .Values.script | nindent 4 }}
 {{- end }}

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: {{ include "k6-test.fullname" . }}-script
# data:
#   test.js: |
# {{ .Values.config.script | indent 4 }}