apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default        # 실제 네임스페이스로 변경
  labels:
    app: backend
spec:
  replicas: 2              # 원하는 복제 수
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: alex62626/matchfit:latest   # CI에서 sed로 교체될 부분
          ports:
            - containerPort: 8080
	  envFrom:
            - configMapRef:
                name: app-config
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu:    "100m"
              memory: "128Mi"
            limits:
              cpu:    "500m"
              memory: "256Mi"

