apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default        # 실제 네임스페이스로 변경
  labels:
    app: backend
spec:
  replicas: 2              # 원하는 복제 수
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: alex62626/matchfit:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
