apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-sa
  namespace: default              # 실제 네임스페이스와 일치시킬 것
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::061039804626:role/matchfit-backend-s3-access-irsa-role
