apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matchfit-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CLD-3rd/Final-Team3-manifests.git
    targetRevision: feat/hpa
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: backend
      namespace: argocd
      jsonPointers:
        - /spec/replicas
  dependsOn:
    - backend-hpa
    - external-dns
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /spec/dependsOn
