apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-hpa
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/CLD-3rd/Final-Team3-manifests.git
    targetRevision: feat/s3-irsa
    path: base/hpa
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

