apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # 전체적인 순서 변경해야 함
spec:
  project: default
  source:
    repoURL: oci://public.ecr.aws/karpenter/karpenter
    chart: karpenter
    targetRevision: "1.6.1"
    helm:
      values: |
        settings:
          clusterName: matchfit-eks
          interruptionQueue: matchfit-eks   # infra에서 만든 SQS name과 일치시킬 것, ${CLUSTER_NAME}이 맞을 듯?
        serviceAccount:
          create: true
          name: karpenter
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::061039804626:role/matchfit-eks-karpenter
        crds:
          install: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system  # 문서 권장 (우선순위 FlowSchema 혜택)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
