apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: oci://public.ecr.aws/karpenter
    chart: karpenter
    targetRevision: v1.6.1
    helm:
      values: |
        settings:
          clusterName: matchfit-eks
          interruptionQueue: matchfit-eks   # infra에서 만든 SQS name과 일치시킬 것
        serviceAccount:
          create: false
          name: karpenter
        crds:
          install: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system  # 문서 권장 (우선순위 FlowSchema 혜택)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

