apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"   # cluster-bootstrap(0), karpenter(1) 이후
spec:
  project: default
  source:
    repoURL: https://kubecost.github.io/cost-analyzer
    chart: cost-analyzer
    targetRevision: 1.104.0
    helm:
      values: |
        prometheus:
          enabled: false
          nodeExporter:
            enabled: false
          server:
            enabled: false
            persistentVolume:
              enabled: false
          alertmanager:
            enabled: false
          pushgateway:
            enabled: false

        grafana:
          enabled: false

        kubecostProductConfigs:
          clusterName: matchfit-eks
          awsRegion: ap-northeast-2

        global:
          prometheus:
            enabled: false
            fqdn: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
          grafana:
            fqdn: false

        serviceMonitor:
          enabled: true
          additionalLabels:
            release: kube-prometheus-stack

        prometheusRule:
          enabled: true
          additionalLabels:
            release: kube-prometheus-stack

        kubecostFrontend:
          ingress:
            enabled: false

        persistentVolume:
          enabled: false

        serviceAccount:
          create: false
          name: kubecost-cost-analyzer

        kubecostModel:
          etl: false
          etlCloudUsage: false
          assetReconciliation: false
          savingsCacheWarming: false
          etlFileStoreEnabled: false
          etlToDiskEnabled: false
          cloudCost:
            enabled: false

          extraEnv:
            - name: AWS_STS_REGIONAL_ENDPOINTS
              value: regional
            - name: ETL_ENABLED
              value: "false"
            - name: ETL_CLOUD_USAGE_ENABLED
              value: "false"
            - name: ETL_ASSET_RECONCILIATION_ENABLED
              value: "false"
            - name: SAVINGS_CACHE_WARMING_ENABLED
              value: "false"
            - name: CLOUD_COST_ENABLED
              value: "false"
            - name: PV_ENABLED
              value: "false"
            - name: PRODUCT_ANALYTICS_ENABLED
              value: "false"
            - name: VALUES_REPORTING_ENABLED
              value: "false"
            - name: ERROR_REPORTING_ENABLED
              value: "false"
            - name: CLOUD_PROVIDER_API_KEY
              value: ""


  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
