apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"   # cluster-bootstrap(0), karpenter(1) 이후
spec:
  project: default
  source:
    repoURL: https://kubecost.github.io/cost-analyzer
    chart: cost-analyzer
    targetRevision: 1.104.0
    helm:
      values: |
        prometheus:
          enabled: false
          nodeExporter:
            enabled: false
          server:
            enabled: false
            persistentVolume:
              enabled: false
          alertmanager:
            enabled: false
          pushgateway:
            enabled: false

        grafana:
          enabled: false

        global:
          prometheus:
            fqdn: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          grafana:
            fqdn: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local

        kubecostProductConfigs:
          prometheusServerEndpoint: "http://prometheus-kube-prometheus-stack.monitoring.svc.cluster.local:9090"
          grafanaURL: "http://grafana.monitoring.svc.cluster.local"

        kubecostFrontend:
          ingress:
            enabled: false

        persistentVolume:
          enabled: false
        etl:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
